---
- name: User creation with loop
  hosts: all
  become: true
  vars:
    users:
    - {name: "Feyi", uid: 1010}
    - {name: "Taiwo", uid: 1020}
    - {name: "Sayo", uid: 1030}
  tasks:
    - name: create users
      user: 
        name: "{{ item.name }}"
        state: present
      loop: "{{ users }}"

